# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-14 01:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', easy_thumbnails.fields.ThumbnailerField(storage=django.core.files.storage.FileSystemStorage(), upload_to='files', verbose_name='File')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('filename', models.CharField(help_text='Use for renaming your file on the server', max_length=255, unique=True, verbose_name='Filename')),
                ('author', models.CharField(blank=True, default='', max_length=255, verbose_name='Author')),
                ('copyright', models.CharField(blank=True, default='', max_length=255, verbose_name='Copyright')),
                ('type', models.CharField(blank=True, max_length=12, verbose_name='File type')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('extension', models.CharField(blank=True, default='', max_length=255, verbose_name='Extension')),
                ('file_hash', models.CharField(help_text='For preventing duplicates', max_length=40, unique=True, verbose_name='Checksum')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filebase.Folder', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filebase.Folder', verbose_name='files'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
