# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-14 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebase.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filebase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='TestGalleryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='description')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.TestGallery')),
                ('image', filebase.fields.FilebaseFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='filebase.File', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Test Gallery ENTRY',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy', models.CharField(blank=True, max_length=255, verbose_name='dummy')),
                ('file', filebase.fields.FilebaseFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filebase.File')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='only for checking out raw_id_fields!', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
